void q1_soma (int *a, int *b, int *resultado);
void q2_subtracao(int *a, int *b, int *resultado);
void q4_divisao(double *a, double *b, double *resultado);
void q7_fatorial(long long int *a, long long int *resultado);
void q9_or(int *a, int *b, int *resultado);
void q11_shift_direita(int *a, int *b, int *resultado);
void q14_somatorio_invervalo(int *a, int *b, int *resultado);
void q16_minimo(int *a, int *b, int *resultado);
void q18_abs(int *a, int *resultado);
void q21_maior_que(int *a, int *b, int *resultado);
void q23_maior_igual(int *a, int *b, int *resultado);
void q25_and(int *a, int *b, int *resultado);
void q28_nor(int *a, int *b, int *resultado);